version: '3'
services:
  api:
    container_name: attend-log-gin-api
    build:
      context: .
      dockerfile: ./docker/api/go/Dockerfile
    tty: true
    volumes:
      - ./api:/var/www
    ports:
      - "3000:3000"
      - "9000:9000"
    depends_on:
      db:
        condition: service_started
    tty: true

  front:
    container_name: attend-log-gin-front
    build:
      context: .
      dockerfile: ./docker/front/node/Dockerfile
    volumes:
      - ./front:/var/www/html
    ports:
      - 8080:8080
    command: |
      sh -c
      'npm install &&
       npm run serve'
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/db/mysql/Dockerfile
    container_name: attend-log-gin-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: attend_log
      MYSQL_USER: attend_log
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    tty: true

volumes:
  mysql-volume: